version: "3.9"

services:
  redis:
    image: redis:7-alpine
    networks:
      - app-network
    restart: always

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  worker:
    build: ./worker
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  app-network: