name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------------------------
      # Python Setup + Lint
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python lint tools
        run: |
          pip install flake8

      - name: Lint Python
        run: |
          flake8 api worker

      # -------------------------
      # Node.js + ESLint
      # -------------------------
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install ESLint
        run: |
          cd frontend
          npm install eslint

      - name: Run ESLint
        run: |
          cd frontend
          npx eslint . || true

      # -------------------------
      # Dockerfile Lint (Hadolint)
      # -------------------------
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: |
            api/Dockerfile
            worker/Dockerfile
            frontend/Dockerfile